### ISSUE TITLE
Shenmue and Ready 2 Rumble Boxing - Sound Issues

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1030]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 187674d

When Ryo walks or runs in the corridor, the sound is extremely low.
[SaveState](https://github.com/flyinghead/flycast/files/11322678/Shenmue.Disc1.zip)

Ready 2 Rumble Boxing has a similar issue where the referee's count can't be heard at times.
[SaveState](https://github.com/flyinghead/flycast/files/11322923/Ready.2.Rumble.Boxing.zip)

**Comment by kihato** [comment]
About Ryo's footsteps.
original link: [https://github.com/libretro/flycast/issues/737](https://github.com/libretro/flycast/issues/737)


fbdbd24: Can be reproduced
afc8398: Cannot reproduce

Temporarily disabling `FEG.active` allows footsteps to be heard, but these sounds seem to be very different from what they are on the real hardware.


The link below is the footsteps on the real hardware.

The sound of Ryo's footsteps walking down the wooden hallway.
[https://youtu.be/IeuCO534448?t=701](https://youtu.be/IeuCO534448?t=701)
The sound of Ryo's footsteps running on the paved road.
[https://youtu.be/IeuCO534448?t=1066](https://youtu.be/IeuCO534448?t=1066)

**Comment by flyinghead** [comment]
Ryo's footsteps not being heard is due to the imperfect implementation of the LPF filter (a.k.a. FEG).
This was improved by bafe07de859abe9f5d3b755de5a1fb20a998f238 on the dev branch. However footsteps are now a bit too loud.
This is linked to issue #108.

**Comment by kihato** [comment]
807e4a2 is a fantastic improvement.
Shenmue's footsteps have been dramatically improved, now feeling just like the real hardware.
Thank you for your great work!

**Comment by flyinghead** [comment]
I'm glad all this work wasn't in vain. And thank you for testing!

**Comment by kihato** [comment]
The issue where the referee's count in Ready 2 Rumble Boxing was sometimes inaudible was fixed in b468c9b, but there was also an issue where the audio would sometimes be delayed when the referee brought his arm down.
However, it turns out this also happens when playing on the real hardware.
https://youtu.be/HW5qsRKBl9M?t=809
So closing this issue. Thank you again!

**Comment by socialenigma-og** [comment]
Thank you so much for this!
Unfortunately, it did not fix Jet Set Radio's sound-effects for the inline rollerskates.
It did, however, fix Skies of Arcadia's footsteps on earth terrain (wooden and metallic floors already played correctly).

**Comment by kihato** [comment]
@socialenigma-og 
I have created an issue (#2107) for jet set radio, so please check it out. Thank you for reporting the bug.
