### ISSUE TITLE
[Bug/Libretro/AMD/Win11/Vulkan]Capcom vs. SNK - Broken menu (left side)

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1085]
The selection menu is broken at the extreme left. The bug is heavy on GL/Vulkan and less pronounced in D3D11.

This is in native res : https://streamable.com/e80u54

I didn't test standalone but it should likely be the same.

**Comment by flyinghead** [comment]
I can't reproduce it here. Likely a GPU issue, which you didn't mention.

**Comment by Immersion95** [comment]
> I can't reproduce it here. Likely a GPU issue, which you didn't mention.

Sorry @flyinghead, I totally forgot. It's happening here with Rx 6800 XT with latest drivers. I tried the Native depth AMD fix but it's crashing before the menu. Do you need a specifig log ?

I will test with 7900 XTX but almost certain that it was the same.

**Comment by flyinghead** [comment]
core and frontend debug log could help

**Comment by Immersion95** [comment]
Here it is : [
[Vulkan.log](https://github.com/flyinghead/flycast/files/11628440/Vulkan.log)
[Vulkan & Native depth crash.log](https://github.com/flyinghead/flycast/files/11628441/Vulkan.Native.depth.crash.log)
](url)

**Comment by flyinghead** [comment]
Unfortunately this looks like a GPU/driver error:
`W[RENDERER]: Vulkan system error vk::Queue::submit: ErrorDeviceLost`

I haven't been able to reproduce it with RA 1.14 or 1.15 and the latest flycast core (linux/nvidia).

**Comment by flyinghead** [comment]
assuming this is fixed. reopen if not

**Comment by Immersion95** [comment]
It's fixed and not fixed.

It's fixed as Native depth solves it.

It's not fixed as Vulkan + Native depth make the game crash as soon as there is an explosion impact between characters.

I'll open another issue.

**Comment by flyinghead** [comment]
Native Depth Interpolation is needed for AMD so this is normal.
For the crash, this is obviously a driver issue so there's nothing I can do.

**Comment by Immersion95** [comment]
Don't have the 6800 XT but it's solved with 7800 XT and latest driver.
