### ISSUE TITLE
Flathub version crash when running games or bios

### ISSUE THREAD

**Issue by espher1987** [flyinghead/flycast#1100]
Platform / OS / Hardware: pc/ Debian 11 stable - linux kernel: 5.10.179-1 Intel® Core™ i3-7020U CPU @ 2.30GHz × 4 - Mesa Intel® HD Graphics 620 (KBL GT2)

Github hash: 

I was trying to run any games in my library, resident evil code veronica for example and bios, sega logo appears but then close.

when i run from console with:
```
flatpak run org.flycast.Flycast 
```

 i get this error:

```
00:00:073 sdl/sdl.cpp:599 N[RENDERER]: Monitor refresh rate: 60 Hz (1366 x 768)
00:00:141 rend/vulkan/vulkan_context.cpp:249 N[RENDERER]: Vulkan API 1.1. Device Intel(R) HD Graphics 620 (KBL GT2)
00:00:141 rend/vulkan/vulkan_context.cpp:257 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
00:00:227 rend/vulkan/vulkan_context.h:266 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:228 rend/gui.cpp:294 N[RENDERER]: Screen DPI is 113, size 683 x 704. Scaling by 1.00
00:00:397 rend/vulkan/vulkan_renderer.cpp:30 N[RENDERER]: VulkanRenderer::Init
00:01:832 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:01:877 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7f1276c80000 RAM(16 MB) 0x7f1282c80000 VRAM64(8 MB) 0x7f127ac80000 ARAM(2 MB) 0x7f1296c80000
00:01:924 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:01:943 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7f1276c80000 RAM(16 MB) 0x7f1282c80000 VRAM64(8 MB) 0x7f127ac80000 ARAM(2 MB) 0x7f1296c80000
00:01:974 emulator.cpp:54 N[BOOT]: Game ID is [T1204N]
00:02:005 emulator.cpp:568 N[BOOT]: Did not load BIOS, using reios
00:02:023 emulator.cpp:54 N[BOOT]: Game ID is [T1204N]
00:02:024 sdl/sdl_gamepad.h:373 N[INPUT]: Resetting SDL gamepad to default: 0 1
00:02:080 reios/reios.cpp:616 N[REIOS]: -----------------
00:02:080 reios/reios.cpp:617 N[REIOS]: REIOS: Booting up
00:02:080 reios/reios.cpp:618 N[REIOS]: -----------------
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = PolyParam; _Alloc = std::allocator<PolyParam>; reference = PolyParam&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

i get this error from

```
Commit: 689858d1b6771d84939b0dffc58737409d85d7bc6dff1734752345eb8775cb1d
Asunto: Update flycast.git (941b01c2)
Fecha: 2023-05-31 17:04:36 +0000
```
or any other version from this to today

for some reason i cant install  this version: 
```
Commit: f7c716eda8df678dd682232c834a125e0300c41936b5c387a7f01a0da3a8b879
Asunto: Update flycast.git (c436f832)
Fecha: 2023-05-30 14:41:16 +0000
```
so i cant be sure if this happend from here:

This error not happend if i force install version:

```
Commit: e5c91dd78c012434f3c73c381e3592a0c992cde7b2f5b653c1f1d59f8afabe98
Asunto: Update flycast.git (0cff2c64)
Fecha: 2023-05-26 23:49:12 +0000
```

or any older version.

i hope this can help to fix it. Thanks for your amazing job.

**Comment by flyinghead** [comment]
Should be fixed by ffc0a42c1805d80cb51601652cbd702ca353c7b8

**Comment by the-importer** [comment]
I'm still seeing the 2023-06-01 built on SteamOS's Discover, do you know when the new one will be pushed?

**Comment by flyinghead** [comment]
Same here but it should be available in the next 24 hours.

**Comment by flyinghead** [comment]
The flatpak update is available

**Comment by espher1987** [comment]
i can confirm, now is working, thanks!

**Comment by espher1987** [comment]
thanks for all!!!

**Comment by majunia28** [comment]
About 6 days and four updates later (flathub version) and still the same problem

I'm using lastest version of Solus OS

00:00:437 sdl/sdl.cpp:599 N[RENDERER]: Monitor refresh rate: 60 Hz (1366 x 768)
00:00:452 rend/gui.cpp:294 N[RENDERER]: Screen DPI is 113, size 1024 x 513. Scaling by 1.00
00:00:517 rend/gles/gles.cpp:562 N[RENDERER]: OpenGL version 4.6
00:03:113 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:03:160 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7fe565450000 RAM(16 MB) 0x7fe571450000 VRAM64(8 MB) 0x7fe569450000 ARAM(2 MB) 0x7fe585450000
00:03:195 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:03:225 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7fe565450000 RAM(16 MB) 0x7fe571450000 VRAM64(8 MB) 0x7fe569450000 ARAM(2 MB) 0x7fe585450000
00:03:344 emulator.cpp:54 N[BOOT]: Game ID is [T3601M]
00:03:344 emulator.cpp:172 N[BOOT]: USA region not supported. Using Japan instead
00:03:347 emulator.cpp:54 N[BOOT]: Game ID is [T3601M]
00:03:347 sdl/sdl_gamepad.h:373 N[INPUT]: Resetting SDL gamepad to default: 0 1
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = PolyParam; _Alloc = std::allocator<PolyParam>; reference = PolyParam&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

**Comment by espher1987** [comment]
> About 6 days and four updates later (flathub version) and still the same problem
> 
> I'm using the lastest version of SolusOS
> 
> 00:00:437 sdl/sdl.cpp:599 N[RENDERER]: Monitor refresh rate: 60 Hz (1366 x 768) 00:00:452 rend/gui.cpp:294 N[RENDERER]: Screen DPI is 113, size 1024 x 513. Scaling by 1.00 00:00:517 rend/gles/gles.cpp:562 N[RENDERER]: OpenGL version 4.6 00:03:113 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled 00:03:160 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7fe565450000 RAM(16 MB) 0x7fe571450000 VRAM64(8 MB) 0x7fe569450000 ARAM(2 MB) 0x7fe585450000 00:03:195 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled 00:03:225 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 0x7fe565450000 RAM(16 MB) 0x7fe571450000 VRAM64(8 MB) 0x7fe569450000 ARAM(2 MB) 0x7fe585450000 00:03:344 emulator.cpp:54 N[BOOT]: Game ID is [T3601M] 00:03:344 emulator.cpp:172 N[BOOT]: USA region not supported. Using Japan instead 00:03:347 emulator.cpp:54 N[BOOT]: Game ID is [T3601M] 00:03:347 sdl/sdl_gamepad.h:373 N[INPUT]: Resetting SDL gamepad to default: 0 1 /usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator [with _Tp = PolyParam; _Alloc = std::allocator; reference = PolyParam&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

that is weird, i completly uninstall and install to be sure and now works fine for me with the last update. Did you try to force an old version?

```
sudo flatpak update --commit=e5c91dd78c012434f3c73c381e3592a0c992cde7b2f5b653c1f1d59f8afabe98 org.flycast.Flycast
```

if this version is not working for you, maybe is not the same problem. This old version works for me.

**Comment by majunia28** [comment]
uninstalling and installing flycast didn't work for me (same problem)
BUT forcing the old version that you suggest works fine. (no crashing)

So, no updates for a while? do they need more info to keep investigating?

**Comment by majunia28** [comment]
Today update it's working at last (tested with BIOS, Soul Calibur and Tomb Raider The Last Revelation, no crashing).
Thanks for your work, guys. <3
