### ISSUE TITLE
Atomiswave port (Samurai Shodown 6)

### ISSUE THREAD

**Issue by jvhellraiser** [flyinghead/flycast#136]
I am getting a lot of Black/missing/out of place textures issues with Samurai Showdown 6 port it to the 
from Atomiswave to the dreamcast i understand Flycast supports loading Atomiswave
roms but is there any fix for the port version texture problems? this issue wont happen on real hardware..

![Screenshot 2020-12-04 100438](https://user-images.githubusercontent.com/16488761/101173057-5fd76a00-3618-11eb-814d-f2f7ce99abe2.jpg)

**Comment by flyinghead** [comment]
Is this an issue specific to the dreamcast port, or does it also happen with the atomiswave rom?

What's your platform?

**Comment by jvhellraiser** [comment]
> 
> 
> Is this an issue specific to the dreamcast port, or does it also happen with the atomiswave rom?
> 
> What's your platform?

In Atomiswave Rom Samurai  Showdown 6 is missing the MAP when showing the Vs area select it....Only issue as i see..
In the Dreamcast port of Samurai Showdown 6  with this one is missing textures alot...

Select Character select/power select screen black textures all over, 
in the fight just like i post it above  characters look broken (missing transparencies?)
missing sky is some stages (Black textures cover the sky)

**Comment by flyinghead** [comment]
Yes, I forgot that this game has some special settings because of depth issues. And the dreamcast port is detected as a different game and doesn't use them.

Any reason why you want to use the dreamcast port?

Do you know the CD product number being used so I can identify it?

**Comment by jvhellraiser** [comment]
The only thing i could get with GD-Rom explorer 
is this info not sure if its any use since i don't have much
expertise in this, but if not I'll ask and try to find it..
![Screenshot 2020-12-04 201753](https://user-images.githubusercontent.com/16488761/101227448-4a8d2a80-366e-11eb-8ba8-ba259f403600.jpg)

**Comment by flyinghead** [comment]
Thank! The last build should fix this issue.

**Comment by jvhellraiser** [comment]
> 
> 
> Thanks! The last build should fix this issue.

Thank for the character Fix no longer the character look broken
thought i want it for you to see what still happening,
when you win a Fight this not only happens on the port version
it happens in the rom version too....
![Screenshot 2020-12-06 123958](https://user-images.githubusercontent.com/16488761/101286734-9b159c80-37c2-11eb-90df-a1ed7362a307.jpg)

Also in this new build when loading this game my bios acted all funny while loading...
![Screenshot 2020-12-06 124425](https://user-images.githubusercontent.com/16488761/101286753-b54f7a80-37c2-11eb-8409-17e90894a23c.jpg)

**Comment by flyinghead** [comment]
This game uses very large depth (Z) values. To compensate for this, depth values are reduced, which may affect other views (such as the BIOS boot).
Also this fixes most issues during a fight, but many depth issues remain on menus, interstitial screens, etc. Unfortunately, fixing one breaks the other and vice-versa...

**Comment by jvhellraiser** [comment]
> 
> 
> This game uses very large depth (Z) values. To compensate for this, depth values are reduced, which may affect other views (such as the BIOS boot).
> Also this fixes most issues during a fight, but many depth issues remain on menus, interstitial screens, etc. Unfortunately, fixing one breaks the other and vice-versa...

ok, understood..good job and thanks for taking time i fix some of the issues that use to happen
very interesting i wish i knew more about the subject always being attracted to the emulation and the
complex of emulating the games

**Comment by flyinghead** [comment]
Fixed

**Comment by Immersion95** [comment]
> This game uses very large depth (Z) values. To compensate for this, depth values are reduced, which may affect other views (such as the BIOS boot). Also this fixes most issues during a fight, but many depth issues remain on menus, interstitial screens, etc. Unfortunately, fixing one breaks the other and vice-versa...

Hey @flyinghead, I don't know if this is of any interest to you but MAME actually renders this game perfectly (albeit at 70-ish % speed).

![samsptk-230729-104306](https://github.com/flyinghead/flycast/assets/47425204/4fd0ea15-2f49-4756-9ae6-98de314b0856)

**Comment by UnionExxis** [comment]
> Fixed

I realize that this issue is marked as Closed and noted as Fixed, but I noticed some z-fighting issues on the character select and subsequent screens. This seems present in both the original Atomiswave and Dreamcast homebrew port. Once you're in-game and fighting, these issues aren't present. Switching Transparency Sorting values from Per Pixel to Per Strip seems to fix the issue in one place but cause issues in another.

I'm using the latest version of Flycast, 2.2 from 10/28/2023. Curious if anyone knows of any settings to dial in this game nicely?

Here's some screenshots:



![Character Select screen](https://i.imgur.com/EnneDi7.png)

![Spirit Select screen](https://i.imgur.com/pUx8BXT.png)

![In-game](https://i.imgur.com/PFOGo0c.png)

**Comment by flyinghead** [comment]
The latest `dev` build has a fix for this game. Feedback welcome.

**Comment by UnionExxis** [comment]
Whoa, nice! I'll give it a test shortly and report back.

**Comment by UnionExxis** [comment]
Can confirm, looks fixed in v2.2-171-g434083c71.

![Screenshot 2024-02-07 222551](https://github.com/flyinghead/flycast/assets/73078011/cedb5a75-c59d-4ea3-905b-1db5088bace5)

**Comment by kihato** [comment]
If the game selects a country that is located below the red center line of the stage map, the texture that indicates this is not displayed.

( Left image: Correct display / Right image: 434083c )
![KOF_XI_05](https://github.com/user-attachments/assets/1651a6bf-bc16-4a55-9ca0-9905badf9492)
