### ISSUE TITLE
ECCO the Dolphin: static background sprites dissapear, game is accelerated

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1614]
**_Platform / OS / Hardware_**
Windows 11 x64

**_Github hash_** 
308d9fc1acee55a58be5a21471680d4694ba983c (Libretro core)

**_Hardware_**
AMD Ryzen 2600, Radeon RX 570, 16GB RAM

**_Description of the Issue_**
Game: "Ecco the Dolphin - Defender of the Future (USA) (En,Fr,De,Es)" GDI version.

Two issues are observed:

1. Static background sprites disappear:
The Sega logo appears, disappears for a second and comes back.
The title screen shows up while it does a fade in animation, disappears for a second and comes back with the text "Press Start Button" animated.
The background image for each chapter's loading screen disappears in similar fashion, but the loading bar shows normally.
It's like unanimated images become invisible.
This issue was present previously but I don't know when it was introduced.

2. Game is accelerated:
This is weird, the games were playing fine yesterday. Today I got the new version of the core and all the games I tested, including ECCO, now seem to run at uncapped FPS. I didn't change any configuration settings. RetroArch's VSync is enabled and tested with ```Threaded Rendering``` ON and OFF but it didn't change the behaviour.

Note: this was using Vulkan API.

**_Video_**
https://github.com/user-attachments/assets/befe7d0b-e556-4843-95c9-ce0ab44a8f66

**Comment by flyinghead** [comment]
1. I think this issue has always been present. It can be fixed by enabling `Full Framebuffer Emulation`. My guess is the game is either directly writing to the framebuffer in VRAM, or manipulating the framebuffer address registers in a way that confuses "normal" rendering.
2. I don't think this is linked with yesterday's changes. Does it also happen when using per-triangle or per-strip? Only per-pixel code was updated yesterday.

**Comment by mfigueirido** [comment]
I see!

Regarding issue #2: Downloaded an old Flycast core and the games are still accelerated, so we can discard a fault in Flycast. Now I have to understand what's happening because the other cores are running at normal speeds.

**Comment by flyinghead** [comment]
The disappearing textures issue should be fixed on master.

**Comment by mfigueirido** [comment]
It's still happening for me with core version b468c9bdae4c5e75e3e39d6f7ff8672696f810f6.

![imaxe](https://github.com/user-attachments/assets/422f33ff-330b-4b36-b226-7b6781cc0fcd)

Anything I can do to help?

**Comment by flyinghead** [comment]
it's not fixed. I made a last minute change that broke it.

**Comment by flyinghead** [comment]
Should be really fixed now on master
