### ISSUE TITLE
Bluetooth audio lagging solution ?

### ISSUE THREAD

**Issue by tabnk** [flyinghead/flycast#182]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android/Q/Phone

Github hash: 
https://github.com/flyinghead/flycast/commit/17e46a1

Hardware: 
Android Phone with Snapdragon 855 and Razer Hammerhead True Wireless Earbuds (Ultra Low Latency at 60ms) 

**_Description of the Issue_**

Audio lagging while using a **Ultra Low Latency Bluetooth Earbuds**. Current workaround was to use RetroArch (Setting Audio Latency: 32ms and Polling behavior: Normal) which can really reach unnoticeable audio lag. 

Are there any **hidden setting such as Audio Latency and Input Polling** within flycast standalone emulator that can be adjusted?

**Comment by flyinghead** [comment]
There is an audio latency setting but it's not exposed in Android at the moment.

**Comment by tabnk** [comment]
Inside the android emu.cfg, there is a line aica.BufferSize = 2822. 

Does this value affect the audio latency?

**Comment by flyinghead** [comment]
The latest build exposes the sound latency setting on Android.

It defaults to automatic, which uses the minimum audio buffer size recommended by the system. For example on a SD 845 running android 10 it is set to 40 ms.

**Comment by tabnk** [comment]
Enabled Auto Latency:  No noticeable change. 

Disabled Auto Latency and set it at 12ms: Latency definitely improved but somehow still got some lag. 

Lastly comparing to RetroArch for Android (Audio Latency at 32ms and Polling behavior at Normal): Almost no lag at all. 

It make me wonder what other factor could affect it. And than I saw the input lag was much higher in flycast standalone than RetroArch. 

Perhaps, the input lag also contribute to overall lagging experience?

Is there some way to shorten the input polling too?

**Comment by tabnk** [comment]
My previous audio lagging tested was done wrongly. Even though Auto Latency was Disabled, 12ms latency was actually not registered at all.  

Tested few more 64ms, 32ms, 16ms, 6ms, 1ms. Basically non of the manual set latency work. Otherwise at 12ms or lower should already had audio crackling sound.

**Comment by flyinghead** [comment]
You are indeed correct. Android limits the minimum buffer size and thus the latency. It turns out that the `Automatic Latency` setting corresponds to the minimum audio buffer size. Setting a latency below this has no effect.

In order to reach lower latency, a different audio API must be used (OpenSL), which is what retroarch uses.

**Comment by flyinghead** [comment]
I just pushed a new native audio driver for android (Oboe). It uses AAudio if available, and falls back to OpenSLES if not. In both cases the audio latency should be less than with the current Java driver.

**Comment by Foxlum** [comment]
@flyinghead Tested improves the situation but doesn't exactly fix it, but definitely a improvement commit 6dfa9f7786e137de98ea89ac22d84836463116c0.

**Comment by tabnk** [comment]
Tried the Oboe driver and it does shorten the audio lag but still cannot reach the same low latency as RetroArch.  Changed the Audio Buffer Size to 12ms but make no difference.

**Comment by tabnk** [comment]
Read from guide here https://github.com/google/oboe/blob/master/docs/FullGuide.md

Maybe changing this mBufferSizeInFrames help in some way.

**Comment by tabnk** [comment]
Tried it on another Phone (**Samsung Galaxy A51** Exynos 9611 with Android 11). No audio lag with Oboe driver. Same low latency as RetroArch. 

Perhaps, I need to wait for Android 11 to be released for my Gaming Phone (Snapdragon 855) to test again.

**Comment by Foxlum** [comment]
> Tried it on another Phone (**Samsung Galaxy A51** Exynos 9611 with Android 11). No audio lag with Oboe driver. Same low latency as RetroArch.
> 
> Perhaps, I need to wait for Android 11 to be released for my Gaming Phone (Snapdragon 855) to test again.

@tabnk Well I have a Pixel 4a 5G, using Android 11 on a Snapdragon 765G. The audio is fine, the frames attached though are "skippy" and frame timing terrible, but better from the recent commit 6dfa9f7786e137de98ea89ac22d84836463116c0 and forcing the lowest latency possible.

**Comment by tabnk** [comment]
> > Tried it on another Phone (**Samsung Galaxy A51** Exynos 9611 with Android 11). No audio lag with Oboe driver. Same low latency as RetroArch.
> > Perhaps, I need to wait for Android 11 to be released for my Gaming Phone (Snapdragon 855) to test again.
> 
> @tabnk Well I have a Pixel 4a 5G, using Android 11 on a Snapdragon 765G. The audio is fine, the frames attached though are "skippy" and frame timing terrible, but better from the recent commit [6dfa9f7](https://github.com/flyinghead/flycast/commit/6dfa9f7786e137de98ea89ac22d84836463116c0) and forcing the lowest latency possible.

Previously got graphic skipping issue. Change default Automatic Frame Skipping from Normal to **disabled**. Fixed the my problem.

**Comment by Foxlum** [comment]
@tabnk @flyinghead Ok after tweaking a few things I found out the Auto Audio backend isn't picking the best choice for my device. It was apparently still was trying to use the original audio engine rather than oboe.

**Comment by flyinghead** [comment]
The Oboe driver is still experimental, so it won't be selected by the `auto` setting. You need to explicitly select it in the audio driver list for now.

Regarding changing the Oboe buffer size, I will try to lower it to the minimum. This size must be a multiple of the audio burst size, and the burst size is determined by the underlying audio hardware. On a SD845 running Android 10, it is set at 797, and the buffer size to 1594 (797 x 2).

If you have access to logcat, you can find out these values for your hardware since they are logged when the audio starts:
```
I/flycast: 02:45:061 oslib/audiobackend_oboe.cpp:92 N[AUDIO]: Oboe driver started. stream capacity: 1594 frames, frames/callback: 512, frames/burst: 797
```

**Comment by tabnk** [comment]
The following log from flycast app. My stream capacity is so much higher than your.

00:00:078 hw/mem/_vmem.cpp:500 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:127 hw/mem/_vmem.cpp:500 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:162 nullDC.cpp:96 N[BOOT]: Game ID is [T3601N]
00:00:165 cheats.cpp:398 N[COMMON]: Applying widescreen hack to game T3601N
00:00:185 oslib/audiobackend_oboe.cpp:72 N[AUDIO]: Oboe driver started. stream capacity: **2658 frames**, frames/callback: 512, frames/burst: 882
00:02:989 oslib/audiobackend_oboe.cpp:77 N[AUDIO]: Oboe driver stopping

[flycast.log](https://github.com/flyinghead/flycast/files/6409419/flycast.log)

**Comment by flyinghead** [comment]
Yes, it seems to depend a lot on the device. Here is the result with some JBL Bluetooth speakers:
```
I/flycast: 03:15:227 oslib/audiobackend_oboe.cpp:90 N[AUDIO]: Oboe driver started. stream capacity: 7974 frames, size: 882 frames, frames/callback: 512, frames/burst: 882
```

Note that in the latest build, I set the buffer size to the burst size as can be seen above (capacity 7974 but size 882).

**Comment by tabnk** [comment]
Tried your new build https://github.com/flyinghead/flycast/commit/5dd15e2. 

Latency was much improved. Flycast audio latency is almost/nearly on par with RetroArch. 

Surprisingly, it also indirectly fixed additional audio lag whenever flycast was restart or exit from emulator menu. 


00:00:686 hw/mem/_vmem.cpp:500 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:736 hw/mem/_vmem.cpp:500 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:766 nullDC.cpp:96 N[BOOT]: Game ID is [T3601N]
00:00:768 cheats.cpp:398 N[COMMON]: Applying widescreen hack to game T3601N
00:00:796 oslib/audiobackend_oboe.cpp:90 N[AUDIO]: Oboe driver started. stream capacity: **11518 frames,** size: 882 frames, frames/callback: 512, frames/burst: 882
00:03:642 oslib/audiobackend_oboe.cpp:95 N[AUDIO]: Oboe driver stopping

[flycast.log](https://github.com/flyinghead/flycast/files/6409451/flycast.log)

**Comment by tabnk** [comment]
My **Snapdragon 855 Phone** finally got Android 11 OS upgrade. Still unable to match the low audio latency as an Samsung Galaxy **A51** Phone . So to concluded it is generally my phone software/hardware issue. 

Thank.
