### ISSUE TITLE
Atomiswave SNK Nvmem Issue

### ISSUE THREAD

**Issue by blisstik** [flyinghead/flycast#208]
Hi Flyinghead,

I know this is not the Libretro git but I'd like to bring to your attention an issue with Nvmem files for SNK Atomiswave roms (i.e., mslug6, etc.).

The issue is that it seems like, after 24hours, the nvmem files are getting corrupt, causing the game to freeze on boot. You get stuck on a yellow-ish screen with some lines. The workaround is to manually delete the nvmem or nvmem2 files.

I am not sure if this is related, but it also freezes when you go into Test mode and try to exit out of it.

This is on a 32bit Nvidia Shield using RetroArch.

I was wondering if somebody can test to see if this is happening in this Standalone and hopefully a fix can happen upstream (this Git) so it can be backported to RetroArch.

**Comment by blisstik** [comment]
I can  erify the exiting out of test mode issue persist. i do see that it creates and saves the nvmem files i  English language. I will tmrw to see if it hangs.

**Comment by flyinghead** [comment]
I confirm that exiting the service menu hangs most of the time. It only seems to happen on arm32 though.

I haven't been able to reproduce the nvmem corruption but the boot sometimes stays on this yellow-ish screen for ages, then moves on.

Still investigating.

**Comment by flyinghead** [comment]
The Atomiswave service menu exit/reset should now work properly on arm32 with build https://github.com/flyinghead/flycast/commit/630d31ba209cb3df7e5831cf530e1a197e9c98a2

**Comment by blisstik** [comment]
Exiting works. The nvmem corruption still exists. If it helps, it seems to be date related (i.e., once 24 hours has passed).

**Comment by flyinghead** [comment]
Could you post your .nvmem file here?

**Comment by flyinghead** [comment]
I can now reproduce the issue. The same .nvmem file will hang on arm32 and work fine on x64.

**Comment by flyinghead** [comment]
This should be fixed in build https://github.com/flyinghead/flycast/commit/ed25d45adb1431e797f84432cebfec56dbf8c0c5

**Comment by blisstik** [comment]
TY it worked!
