### ISSUE TITLE
Dead or Alive 2/Millenium - game freezes midway through the 2nd attract mode sequence 

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#377]
Windows 10
f38a7b1
HP Elitebook 8470p Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz 
The game crashes midway the second attract mode sequence of the game
In the 2nd half of the attract mode it shows the tag team battle option available in the game, but when it goes to the beginning of this section the game locks up.
*All my options in Flycast Dojo are default, and i'm using the latest version of the rollback builds on the GitHub page
*I can not find a way to recreate the crash, and i remember in the past it also crashed on the RetroArch build of Flycast.
*And yes, i am using the recommended romset for NAOMI games. 

![Flycast Dojo 9_29_2021 8_49_14 AM](https://user-images.githubusercontent.com/91135037/135271527-a8e5dd75-73e8-417c-8be8-6f30b96f9f34.png)

**Comment by crashGG** [comment]
It appears not only in the doa2m but also doa2 and doa2a.

I am using the recommended romset for NAOMI games,the newest flycast  and RA+flycast core.

**Comment by flyinghead** [comment]
yes, this is a known issue.

**Comment by Tasosgemah** [comment]
Crashes in RetroArch too, always in the part with the machinery, during the second demo loop.

**Comment by flyinghead** [comment]
It looks like this is fixed by 7cc77b10ed5e59db42947128d8715ff415bbe8d7. Check latest `dev` build

**Comment by Tasosgemah** [comment]
> yes,it has been fixed. test with latest dev build.

Still crashes in RetroArch after updating the core today.

**Comment by Tasosgemah** [comment]
Does the RetroArch core gets it's updates from the master build? Because the game still crashes at the usual spot.

**Comment by Tasosgemah** [comment]
4a0ace5 still has this issue.

**Comment by crashGG** [comment]
> [4a0ace5](https://github.com/flyinghead/flycast/commit/4a0ace5de2fd07fcf6c8e7d3c7d8f3c48d4d4581) still has this issue.

This fix has not yet been merged into the mainline, you need to try the latest dev build, or continue to wait.
