### ISSUE TITLE
Latest RA Core boots once but then never again Nvmem issue?

### ISSUE THREAD

**Issue by sagman76** [flyinghead/flycast#439]
Platform / OS / Hardware: Android / Shield Tablet LTE / AOSP 5.8 ROM 

Upon installing latest core it boots fine first time. Any subsequent boots after quitting RA it crashes on launch

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.9.14 (Git e954a46)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec  6 2021
[INFO] Version: 1.9.14
[INFO] Git: e954a46
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 720x720.
[Video]: Starting threaded video driver ...
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x9ce55780.
[GL]: Vendor: NVIDIA Corporation, Renderer: NVIDIA Tegra.
[GL]: Version: OpenGL ES 3.2 NVIDIA 361.00.
[GL]: Using resolution 1920x1200.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
Setting up menu pipeline shaders for XMB ...
[GLSL]: Compiling ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling simple ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling modern snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling bokeh shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snowflake shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Font]: Using font rendering backend: "stb-unicode".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Display]: Found display driver: "gl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[SRAM]: SRAM will not be saved.
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
WindowFocusChanged: 0xa22d45c0 -- 0
WindowFocusChanged: 0xa22d45c0 -- 1
Pause: 0xa22d45c0
WindowFocusChanged: 0xa22d45c0 -- 0
NativeWindowDestroyed: 0xa22d45c0 -- 0x9a425808
SaveInstanceState: 0xa22d45c0
Stop: 0xa22d45c0
Start: 0xa22d45c0
Result: 32512
Resume: 0xa22d45c0
NativeWindowCreated: 0xa22d45c0 -- 0x8bd2e008
WindowFocusChanged: 0xa22d45c0 -- 1
Threaded video stats: Frames pushed: 1789, Frames dropped: 0.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 720x720.
[Video]: Starting threaded video driver ...
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x9ce55740.
[GL]: Vendor: NVIDIA Corporation, Renderer: NVIDIA Tegra.
[GL]: Version: OpenGL ES 3.2 NVIDIA 361.00.
[GL]: Using resolution 1920x1200.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
Setting up menu pipeline shaders for XMB ...
[GLSL]: Compiling ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling simple ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling modern snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling bokeh shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snowflake shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Font]: Using font rendering backend: "stb-unicode".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Display]: Found display driver: "gl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Input]: Game Focus => OFF
[Core]: Using content: "/storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Dreamcast/roms/Cannon Spike (USA).chd".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 504, Frames dropped: 0.
RetroArch 1.9.14 (Git e954a46)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec  6 2021
[INFO] Version: 1.9.14
[INFO] Git: e954a46
[INFO] =================================================
jni_thread_destruct()
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/flycast_libretro_android.so"
[Overrides]: Core-specific overrides found at "/sdcard/RetroArch/config/Flycast/Flycast.cfg".
[Overrides]: No content-dir-specific overrides found at "/sdcard/RetroArch/config/Flycast/roms.cfg".
[Overrides]: Game-specific overrid
[retroarch__2021_12_10__12_06_03.log](https://github.com/flyinghead/flycast/files/7692615/retroarch__2021_12_10__12_06_03.log)
es found at "/sdcard/RetroArch/config/Flycast/Cannon Spike (USA).cfg".
[Overrides]: Game-specific overrides stacking on top of previous overrides.
[Config]: Appending config "/sdcard/RetroArch/config/Flycast/Flycast.cfg".
[Config]: Appending config "/sdcard/RetroArch/config/Flycast/Cannon Spike (USA).cfg".
[Environ]: GET_CORE_OPTIONS_VERSION.
[Environ]: GET_LANGUAGE: "0".
[Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[Environ]: SET_CONTROLLER_INFO.
[Remaps]: Remap directory: "/storage/emulated/0/RetroArch/config/remaps".
[Remaps]: Core-specific remap found at "/storage/emulated/0/RetroArch/config/remaps/Flycast/Flycast.rmp".
[Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/Cannon Spike (USA).srm".
[Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/Cannon Spike (USA).state".
[Environ]: GET_LOG_INTERFACE.
shell/libretro/libretro.cpp:256 N[BOOT]: retro_init
[Environ]: GET_PERF_INTERFACE.
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_KEYBOARD_CALLBACK.
[Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[Content]: Content loading skipped. Implementation will load it on its own.
shell/libretro/libretro.cpp:1518 N[BOOT]: retro_load_game: /storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Dreamcast/roms/Cannon Spike (USA).chd
[Environ]: GET_RUMBLE_INTERFACE.
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: GET_SAVE_DIRECTORY.
[Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
File extension is: .chd
[Environ]: GET_PREFERRED_HW_RENDER, video driver name: gl.
[Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_OPENGL.
[Environ]: SET_HW_RENDER, context type: gl.
Requesting OpenGLES3 context.
Reached end of SET_HW_RENDER.
core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
Verify Failed  : !sh4_int_bCpuRun
 in Sh4_int_Reset -> /builds/libretro/flycast-upstream/core/hw/sh4/interpr/sh4_interpreter.cpp : 92
shell/libretro/libretro.cpp:2773 E[COMMON]: DEBUGBREAK!

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
It looks like a virtual memory initialization issue on the second run:
```
core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
```

I pushed a tentative fix. Let me know if it fixes the issue.

**Comment by sagman76** [comment]
> It looks like a virtual memory initialization issue on the second run:
> 
> ```
> core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
> ```
> 
> I pushed a tentative fix. Let me know if it fixes the issue.

Excuse my lack of knowledge here but how do I get the fix. Do I need to patch something myself or download the core again through RA or via Libretro. Thank you.

**Comment by flyinghead** [comment]
Just update the flycast core with RetroArch as you normally would. The new core version should be available tomorrow.

**Comment by sagman76** [comment]
> Just update the flycast core with RetroArch as you normally would. The new core version should be available tomorrow.

That's great. Many thanks and really appreciate the work and effort you put into Flycast.

**Comment by sagman76** [comment]
> It looks like a virtual memory initialization issue on the second run:
> 
> ```
> core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
> ```
> 
> I pushed a tentative fix. Let me know if it fixes the issue.

Hey Man. Still crashing on any boots after the first boot 

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.9.14 (Git cb8a589)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec 10 2021
[INFO] Version: 1.9.14
[INFO] Git: cb8a589
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 720x720.
[Video]: Starting threaded video driver ...
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0xa371da80.
[GL]: Vendor: NVIDIA Corporation, Renderer: NVIDIA Tegra.
[GL]: Version: OpenGL ES 3.2 NVIDIA 361.00.
[GL]: Using resolution 1920x1200.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
Setting up menu pipeline shaders for XMB ...
[GLSL]: Compiling ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling simple ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling modern snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling bokeh shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snowflake shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Font]: Using font rendering backend: "stb-unicode".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Display]: Found display driver: "gl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[SRAM]: SRAM will not be saved.
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Core]: Using content: "/storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Dreamcast/roms/Power Stone 2 (USA).chd".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 570, Frames dropped: 0.
RetroArch 1.9.14 (Git cb8a589)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec 10 2021
[INFO] Version: 1.9.14
[INFO] Git: cb8a589
[INFO] =================================================
jni_thread_destruct()
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/flycast_libretro_android.so"
[Overrides]: Core-specific overrides found at "/sdcard/RetroArch/config/Flycast/Flycast.cfg".
[Overrides]: No content-dir-specific overrides found at "/sdcard/RetroArch/config/Flycast/roms.cfg".
[Overrides]: Game-specific overrides found at "/sdcard/RetroArch/config/Flycast/Power Stone 2 (USA).cfg".
[Overrides]: Game-specific overrides stacking on top of previous overrides.
[Config]: Appending config "/sdcard/RetroArch/config/Flycast/Flycast.cfg".
[Config]: Appending config "/sdcard/RetroArch/config/Flycast/Power Stone 2 (USA).cfg".
[Environ]: GET_CORE_OPTIONS_VERSION.
[Environ]: GET_LANGUAGE: "0".
[Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[Environ]: SET_CONTROLLER_INFO.
[Remaps]: Remap directory: "/storage/emulated/0/RetroArch/config/remaps".
[Remaps]: Core-specific remap found at "/storage/emulated/0/RetroArch/config/remaps/Flycast/Flycast.rmp".
[Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/Power Stone 2 (USA).srm".
[Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/Power Stone 2 (USA).state".
[Environ]: GET_LOG_INTERFACE.
shell/libretro/libretro.cpp:256 N[BOOT]: retro_init
[Environ]: GET_PERF_INTERFACE.
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_KEYBOARD_CALLBACK.
[Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[Content]: Content loading skipped. Implementation will load it on its own.
shell/libretro/libretro.cpp:1518 N[BOOT]: retro_load_game: /storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Dreamcast/roms/Power Stone 2 (USA).chd
[Environ]: GET_RUMBLE_INTERFACE.
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: GET_SAVE_DIRECTORY.
[Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
File extension is: .chd
[Environ]: GET_PREFERRED_HW_RENDER, video driver name: gl.
[Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_OPENGL.
[Environ]: SET_HW_RENDER, context type: gl.
Requesting OpenGLES3 context.
Reached end of SET_HW_RENDER.
core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
core/hw/mem/_vmem.cpp:485 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
Verify Failed  : !sh4_int_bCpuRun
 in Sh4_int_Reset -> /builds/libretro/flycast-upstream/core/hw/sh4/interpr/sh4_interpreter.cpp : 92
shell/libretro/libretro.cpp:2773 E[COMMON]: DEBUGBREAK!

**Comment by flyinghead** [comment]
I pushed another change, and added some logging to help troubleshoot the issue. It should be on the buildbot tomorrow.

**Comment by sagman76** [comment]
> I pushed another change, and added some logging to help troubleshoot the issue. It should be on the buildbot tomorrow.

Thanks for the further update but still the same on second boot thereafter

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.9.14 (Git cb8a589)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec 10 2021
[INFO] Version: 1.9.14
[INFO] Git: cb8a589
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 720x720.
[Video]: Starting threaded video driver ...
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x9dc9da80.
[GL]: Vendor: NVIDIA Corporation, Renderer: NVIDIA Tegra.
[GL]: Version: OpenGL ES 3.2 NVIDIA 361.00.
[GL]: Using resolution 1920x1200.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
Setting up menu pipeline shaders for XMB ...
[GLSL]: Compiling ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling simple ribbon shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling modern snow shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling bokeh shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Compiling snowflake shader..
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Font]: Using font rendering backend: "stb-unicode".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Display]: Found display driver: "gl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[SRAM]: SRAM will not be saved.
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Font]: Using font rendering backend: "stb-unicode".
[Core]: Using content: "/storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Naomi/roms/ausfache.zip".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 292, Frames dropped: 0.
RetroArch 1.9.14 (Git cb8a589)
=== Build =======================================
Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Dec 10 2021
[INFO] Version: 1.9.14
[INFO] Git: cb8a589
[INFO] =================================================
jni_thread_destruct()
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/flycast_libretro_android.so"
[Overrides]: Core-specific overrides found at "/storage/emulated/0/RetroArch/config/Flycast/Flycast.cfg".
[Overrides]: No content-dir-specific overrides found at "/storage/emulated/0/RetroArch/config/Flycast/roms.cfg".
[Overrides]: No game-specific overrides found at "/storage/emulated/0/RetroArch/config/Flycast/ausfache.cfg".
[Config]: Appending config "/storage/emulated/0/RetroArch/config/Flycast/Flycast.cfg".
[Environ]: GET_CORE_OPTIONS_VERSION.
[Environ]: GET_LANGUAGE: "0".
[Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[Environ]: SET_CONTROLLER_INFO.
[Remaps]: Remap directory: "/storage/emulated/0/RetroArch/config/remaps".
[Remaps]: Core-specific remap found at "/storage/emulated/0/RetroArch/config/remaps/Flycast/Flycast.rmp".
[Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/ausfache.srm".
[Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/ausfache.state".
[Environ]: GET_LOG_INTERFACE.
shell/libretro/libretro.cpp:253 N[BOOT]: retro_init
[Environ]: GET_PERF_INTERFACE.
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_KEYBOARD_CALLBACK.
[Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[Content]: Content loading skipped. Implementation will load it on its own.
shell/libretro/libretro.cpp:1517 N[BOOT]: retro_load_game: /storage/CE90B75F90B74D29/Hyperspin/Roms/Sega Naomi/roms/ausfache.zip
[Environ]: GET_RUMBLE_INTERFACE.
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: GET_SAVE_DIRECTORY.
[Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
File extension is: .zip
[Environ]: GET_PREFERRED_HW_RENDER, video driver name: gl.
[Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_OPENGL.
[Environ]: SET_HW_RENDER, context type: gl.
Requesting OpenGLES2 context.
Reached end of SET_HW_RENDER.
[Environ]: GET_SAVE_DIRECTORY.
core/hw/mem/_vmem.cpp:486 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
core/hw/mem/_vmem.cpp:486 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
Verify Failed  : !sh4_int_bCpuRun
 in Sh4_int_Reset -> /builds/libretro/flycast-upstream/core/hw/sh4/interpr/sh4_interpreter.cpp : 92
shell/libretro/libretro.cpp:2769 E[COMMON]: DEBUGBREAK!

**Comment by flyinghead** [comment]
What is the version of the core you updated to? I added some logging messages and I don't see them in the new log.

**Comment by flyinghead** [comment]
Thanks, that's the expected version.

So it looks like there could be some major memory corruption since it's not even trying to initialize the virtual memory. Also I did some tests with disabling virtual memory and the core doesn't crash (virtual memory support is optional).
In your case it's failing when trying to reset the system as it detects that the CPU is running, which is obviously wrong.

**Comment by sagman76** [comment]
> Thanks, that's the expected version.
> 
> So it looks like there could be some major memory corruption since it's not even trying to initialize the virtual memory. Also I did some tests with disabling virtual memory and the core doesn't crash (virtual memory support is optional). In your case it's failing when trying to reset the system as it detects that the CPU is running, which is obviously wrong.

Okey Dokey. Can I do anything on the tablet  or is it something your end? or will i just be stuck on 0.1 version?

**Comment by flyinghead** [comment]
I doubt you can do anything on your end, besides upgrading your ROM to the latest one available, just in case.

I have absolutely no idea what's going on and nobody reported any similar issue so I'm pretty stuck at the moment.

**Comment by sagman76** [comment]
> I doubt you can do anything on your end, besides upgrading your ROM to the latest one available, just in case.
> 
> I have absolutely no idea what's going on and nobody reported any similar issue so I'm pretty stuck at the moment.

Ahh shoot. Ok thanks for looking into it. It is a custom ROM as NVidia last update broke the tablet pretty much and was awful. Maybe i'll try lineage 15.1 see if that helps. Thanks again

**Comment by flyinghead** [comment]
For what it's worth I'm using Lineage 18 myself on a POCO F1 without issue

**Comment by sagman76** [comment]
> For what it's worth I'm using Lineage 18 myself on a POCO F1 without issue

15.1 is the last real stable rom for it. 16.0 is in development by someone over at xda but it  is buggy as heck. currently.

**Comment by sagman76** [comment]
> For what it's worth I'm using Lineage 18 myself on a POCO F1 without issue

I changed Rom to a debloated stock rom for shield tablet and no issues with the latest core.
