### ISSUE TITLE
Duplicate frames for directx11

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#520]
So after a long period of testing i have concluded that frame pacing issues in 30 fps games would be really helped by being able to to duplicate frames in direct x 11 and maybe gl, users without gsync monitors etc would benefit from this and would not have to force their refresh rate to 30 hz to improve pacing which impacts input lag severely.

Related to: https://github.com/flyinghead/flycast/issues/479 my initial tests

**Comment by Chaseroni** [comment]
I’d just like to add on that this would greatly enhance the experience on android as well under the GL renderer, if it’s possible!

**Comment by jeremy27041980** [comment]
Third !

**Comment by RiasatSalminSami** [comment]
Would be really nice to have a feature like this, especially on phones since there is no way to force Half Vsync from GPU drivers on phone.

On pc, at least with nvidia gpu, forcing standard half vsync from nvidia inspector [standard half is required.  Adaptive half vsync results in vsync to disengage at 30 fps cap and starts to tear+ stutter anyway] and then using special K to cap the emulator at 30 fps does seem to significantly reduce the stutter. But the process is inconvenient and also caps the whole game to 30 even on menus and start-up logo that can be 60 fps, not to mention, the 30 fps cap has to be disengaged every time I need to play  a 60 fps game.

Having the emulator to do the duplication natively will solve all these issues. This should be optional though, since on some slower hardware, duplication might result in slow downs. So for those hardwares, you'd be better off turning off duplication and just play with the stutters at full speed instead of slowing down.

**Comment by bryc** [comment]
I'm experiencing this issue as well under Windows 10. Happens in both standalone and libretro.

Whenever a game is in "30 FPS mode", the frame rate is not smooth, it is intermittently choppy. 

Flycast:

https://github.com/flyinghead/flycast/assets/1408749/d7e6d1d3-a2ea-44cb-8ec8-29874862a61d

Redream:

https://github.com/flyinghead/flycast/assets/1408749/67756d41-9bc3-45b2-bb41-3653d607fb0d


I don't have HW to test, but this video of a Dead or Alive 2 intro cutscene on real hardware shows smooth 30fps movement, whereas in Flycast, it's still somewhat choppy.

Real hardware (not my video, from https://youtu.be/y1F-kWiM71k?t=65):

https://github.com/flyinghead/flycast/assets/1408749/ff9e9496-12c9-41b0-a779-d68cc24443e3

Flycast:

https://github.com/flyinghead/flycast/assets/1408749/1c04dc63-13a3-4353-9dc5-c9291834232d

**Comment by Immersion95** [comment]
Framebuffer doesn't do the trick anymore and I still have uneven framepacing with VRR. I need to enable Vsync to solve it.

**Comment by nexus382** [comment]
I am willing to stress test any thing that's needed.... but now I have moved from redream to flycast.... the ONLY thing I miss.... is everything playing at "60fps" on redream....that made the games much smoother. I know it's duplicating frames... maybe it's just allowing for better frame timing... hense the smoother apperance... but I think it's more than that. I have used programs that will take a video with 30 fps
.. and make it 60....and while it won't look as good as native 60fps... there is a decent improvement. 

ORIGINAL  FRAMES 1,2,3,
NEW  FRAMES 1,1.5,2,2.5,3,3.5


Rather then just duplicating, iv seen scripts/programs that will take frame 1  AND 2... make them both semi transparent... then overlap them.... and THATS frame 1.5  .....   I almost feel redream is doing this due to the pretty big difference playing the same games on both. Redream lacks the Dreamcast Majik, I call it, and redream to me is explained as a sophisticated robot...that does things very....to the rules... and flycast utilizes the DC MAJIK, [1st lvl of SA1. You run on the pier while camera panning s around u, holding up the whole time on original HW, OR flycast... this works perfect... redream... tries to take the scene to litteraly and as camera moves and the point of view does sonic stops running this perfect "predefined" path.] And has that home cooked, sit by the fireplace, good ole dreamcast majik. Seems many people feel that this would be a great upgrade for flycas⁷t. I'm a video/image recovery....not specialist... but i have the tools and know enough to be dangerous...so if I can help if this ever starts to come together.... please, ask.

**Comment by CookiePLMonster** [comment]
For what it's worth, it still seems to be an issue, very much noticeable e.g. in Sega GT, a 30FPS title. While the FPS counter shows 30 continuously, the resulting image is choppier than what one would expect from "just" 30FPS.

**Comment by vanfanel** [comment]
> For what it's worth, it still seems to be an issue, very much noticeable e.g. in Sega GT, a 30FPS title. While the FPS counter shows 30 continuously, the resulting image is choppier than what one would expect from "just" 30FPS.

As things are, "Full Frame buffer Emulation" is needed to achieve correct frame pacing in 30 FPS games.
Ideally that shouldn't be needed for correct frame pacing.

**Comment by RiasatSalminSami** [comment]
Yeah, 30 FPS titles are still a stuttery mess.

**Comment by vanfanel** [comment]
> > As things are, "Full Frame buffer Emulation" is needed to achieve correct frame pacing in 30 FPS games.
> > Ideally that shouldn't be needed for correct frame pacing.
> 
> I tried that and unfortunately it doesn't seem to make a difference (and I don't have VRR).

It works on the RetroArch core at least.

**Comment by flyinghead** [comment]
Fixed a while ago

**Comment by RiasatSalminSami** [comment]
Is there any particular option I need to turn on to fix the stuttering? Tried the latest release and the frame pacing issue is still there unless I enable "full frame buffer" which disables upscaling.

**Comment by flyinghead** [comment]
Get the latest `master` build

**Comment by RiasatSalminSami** [comment]
> Get the latest `master` build

Tested. Looks like you have to enable "vsync" otherwise the framepacing is still poor and results in stutters. But it does work, so that's nice.

Some feedbacks:

When using full frame buffer, the mouse cursor for lightgun games move at 60 fps and has less input latency as a result. When having full frame buffer disabled to upscale games + vsync enabled to make the framepacing better- the lightgun cursor moves at 30 fps and also results in huge input delay.
