### ISSUE TITLE
dolphin blue freeze

### ISSUE THREAD

**Issue by Anths2016** [flyinghead/flycast#62]
Dolphin blue freeze after some seconds from start.

**Comment by flyinghead** [comment]
It doesn't

**Comment by Anths2016** [comment]
https://vimeo.com/404514472

**Comment by Anths2016** [comment]
Sometimes in the beginning, it sure crashes at this level:
https://iili.io/JxkkcG.png

**Comment by flyinghead** [comment]
Yes, the crash at the last level is a known problem. I don't have any fix yet.

**Comment by flyinghead** [comment]
Should be fixed in build https://github.com/flyinghead/flycast/commit/b3de6a166df68e972d3bed44d25806123b773673

**Comment by jsjyqz** [comment]
> Should be fixed in build [b3de6a1](https://github.com/flyinghead/flycast/commit/b3de6a166df68e972d3bed44d25806123b773673)
the final misson still crash after you played in a few minutes

**Comment by flyinghead** [comment]
I just finished the game without crash.

Check your build number and don't use an old savestate as it could be corrupted. Also share your platforms details.

**Comment by jsjyqz** [comment]
> I just finished the game without crash.
> 
> Check your build number and don't use an old savestate as it could be corrupted. Also share your platforms details.

ok，thanks for reply!

**Comment by flyinghead** [comment]
This should be fixed. Re-open as needed.
