### ISSUE TITLE
Trigger Heart Exelica high input lag

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#691]
Platform / OS / Hardware: win10 1809

Github hash: с77с3ab

Hardware: intel i3 + hd 5300 + dx11

Issue:

Trigger Heart Exelica Keypress delay

trgheart , trghearto Keypress delay  about 2 seconds delay, appearing in both standalone and libretro

**Comment by flyinghead** [comment]
Similar to https://github.com/libretro/flycast/issues/719

**Comment by flyinghead** [comment]
This should be fixed on the dev branch

**Comment by crashGG** [comment]
Yes, has been fixed.

**Comment by blisstik** [comment]
Hello - when is the dev merging into main?

**Comment by normchomsky** [comment]
Still getting input lag with this one. Has the fix been added to the main

**Comment by flyinghead** [comment]
no, still on the dev branch

**Comment by flyinghead** [comment]
now on master

**Comment by blisstik** [comment]
TY working great on Xbox Series S
