### ISSUE TITLE
Mat Hoffman's Pro BMX: Missing text and crash on exit

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#878]
Platform / OS / Hardware: 
Windows 10 LTSC

Github hash: 
1e195b7237afceeef725e4f45afd9821e34bf53c

Hardware: 
Ryzen 3600 and GTX 1660 Super

**_Description of the Issue_**

Text is missing on pause screen, and Flycast crashes when exiting to main menu ingame

**_Debugging Steps Tested_**

  * Changing the internal resolution sometimes causes the text to appear or disappear
  * Crashes on both standalone and Retroarch
  * Redump verified .bin / .cue

**_Screenshots_**

Looks like this:
![MHPB](https://user-images.githubusercontent.com/122717331/212552681-a1208d3f-f2e4-4d5f-94cc-70eae57e169e.png)
Should look like this:
![MHPB 2](https://user-images.githubusercontent.com/122717331/212552731-9a13cb83-03ee-4079-a5d4-967b0044df77.png)

**Comment by flyinghead** [comment]
I can reproduce and will have a fix soon for the freeze when exiting to main menu.

However I can't reproduce the issue with the pause text missing. I tried switching resolution and both per-triangle and per-pixel for OpenGL and Vulkan. What are your settings? Do you have a reproducible scenario?

**Comment by flyinghead** [comment]
The freeze should be fixed on latest master

**Comment by fwo7LHzj** [comment]
Thank you, no more freezing.
Still missing text on Windows, Flatpak and Retroarch.
Using Vulkan and per-pixel, I was able to reproduce it by changing internal resolution until the text disappears.
The TRICK letters do not disappear on the pause menu, if that helps.
![Screenshot_20230116_160345](https://user-images.githubusercontent.com/122717331/212607848-05e3afdf-c343-40d6-ab69-a64e2e809759.png)

**Comment by flyinghead** [comment]
Yeah I was able to reproduce it when upscaling like crazy. What's happening is you are overflowing the pixel buffer (512 MB by default) so the menu text (which is transparent) doesn't appear. You may also start seeing glitches on some parts of the screen.

Anyway, increasing the pixel buffer size to 1 GB fixed the problem for me. I suggest you use a reasonable upscaling level to avoid future issues.

**Comment by flyinghead** [comment]
Does it happen only with Vulkan? What about OpenGL and DX11?
Only with per pixel?
Any hint appreciated.

**Comment by fwo7LHzj** [comment]
Yes, it seems to only happen with Vulkan and per-pixel.
It may take many tries until text disappears though, seems to be random.
Deleted config file and only changed those two settings.

**Comment by normchomsky** [comment]
tested and confirmed

**Comment by kihato** [comment]
I'm not sure if it will help, but I thought of an easy way to reproduce this problem.

Widescreen enabled (to display 4:3 off-screen textures)
Vulkan Per-Pixel / 860x480(Native) / Pixel Buffer Size: 512MB / Texture Upscaling: 1
[vmu_save_A1.zip](https://github.com/flyinghead/flycast/files/12705798/vmu_save_A1.zip)

The steps are as follows:

Once you have loaded the file that allows you to select all courses, press the B button to go back and select Free Ride.
Start the game by selecting Hoffman Bike Factory, then stop it and reselect THPS1 WareHouse in level select.

Immediately after starting the game, you can see that the wooden boxes on the right side has turned green.
Next, press the start button to pause, then pause flycast, select PerStrip, immediately select PerPixel again, and cancel the pause after setting is complete.
Then the text will no longer be displayed and the texture will be displayed correctly instead.

![Mat_Hoffman_001](https://github.com/flyinghead/flycast/assets/14366233/ee6d971f-aaa9-48df-b6b8-027cf4395db8)

Move forward a little and once the wooden boxes is out of the screen, repeat the above steps.
The text is now visible again.

![Mat_Hoffman_002](https://github.com/flyinghead/flycast/assets/14366233/55423062-24c9-4b4d-8c96-32f9af38ce4f)

Also, even if the wooden boxes is destroyed, the text can be redisplayed using the same procedure.

![Mat_Hoffman_003](https://github.com/flyinghead/flycast/assets/14366233/d1789874-c78e-42c2-93d1-d2bc951e739e)

**Comment by flyinghead** [comment]
It does help a lot. Thank you!
There is a mix between pipelines, which either makes the wooden boxes green, or makes the text disappears, depending on which graphic pipeline is created first. This explains why you get different results depending on when the renderer is reset.

**Comment by flyinghead** [comment]
Should be fixed in the latest master build
